### PR TITLE
Add pushbutton appearance for radio buttons

### PR DESCRIPTION
**Pull request by alankilborn**
Add pushbutton appearance for radio buttons

### CODE REVIEW

**Comment by alankilborn** [comment]
Just recording a nice reference I found on BS_PUSHLIKE:  https://devblogs.microsoft.com/oldnewthing/20070921-00/?p=25023

**Comment by Ekopalypse** [comment]
> Just recording a nice reference ...

Isn't this already possible?

~~~py
from WinDialog import Dialog, create_dialog_from_rc

rc3 = '''
1 DIALOGEX 0, 0, 374, 289
STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP
CAPTION "Test Results"
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL
FONT 9, "Segoe UI"
{
   CONTROL "", 1, COMBOBOX, CBS_DROPDOWNLIST | WS_CHILD | WS_VISIBLE | WS_VSCROLL | WS_TABSTOP, 2, 2, 224, 30
   CONTROL "Peek Information", -1, BUTTON, BS_GROUPBOX | WS_CHILD | WS_VISIBLE | WS_TABSTOP, 2, 16, 369, 272
   CONTROL "", 2, EDIT, ES_LEFT | ES_MULTILINE | ES_READONLY | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_VSCROLL | WS_TABSTOP, 6, 26, 362, 259
   CONTROL "P 1.0", 0, BUTTON, BS_AUTOCHECKBOX | BS_PUSHLIKE | WS_CHILD | WS_VISIBLE, 229, 2, 34, 13
   CONTROL "P 2.0", 1, BUTTON, BS_AUTOCHECKBOX | BS_PUSHLIKE | WS_CHILD | WS_VISIBLE, 265, 2, 34, 13
   CONTROL "P 2.2", 2, BUTTON, BS_AUTOCHECKBOX | BS_PUSHLIKE | WS_CHILD | WS_VISIBLE, 301, 2, 34, 13
   CONTROL "P 3.0", 3, BUTTON, BS_AUTOCHECKBOX | BS_PUSHLIKE | WS_CHILD | WS_VISIBLE, 337, 2, 34, 13
}
'''

dlg = create_dialog_from_rc(rc_code=rc3)
dlg.show()
~~~

**Comment by alankilborn** [comment]
>Isn't this already possible?

Yes, but I don't use the "create from rc" capability of WinDialog.

**Comment by Ekopalypse** [comment]
create_dialog_from_rc and the dialogs created in "class-style" should hopefully behave in the same way.

~~~py
from WinDialog import Dialog, GroupBox, RadioButton
from WinDialog.controls.button import BS

class ButtonDialog(Dialog):
    def __init__(self, title='Some buttons dialog'):
        super().__init__(title)
        self.size = (250, 200)
        self.center = True
        
        self.btn1 = GroupBox('Group Box 1', (160, 30), (10, 50))
        self.btn2 = RadioButton('Radio button 1', (60,14), (20, 60))
        self.btn2.style += BS.PUSHLIKE
        self.btn3 = RadioButton('Radio button 2', (60,14), (90, 60))
        self.btn3.style += BS.PUSHLIKE

        self.show()

ButtonDialog()
~~~

**Comment by alankilborn** [comment]
Ah, I didn't consider that.
Perhaps you should unmerge this PR (as existing capability was sufficient)?

**Comment by Ekopalypse** [comment]
hmm ... I don't know, I'm undecided, but no, let's leave it.

**Pull request merged**
